### ISSUE TITLE
小程序里Module的生命周期是全局的？

### ISSUE THREAD

**Issue by xilin** [icindy/WxNotificationCenter#1]
看实现是声明了一个notice数组，这个数组的生命周期是保证全局唯一的吗？

**Comment by icindy** [comment]
是的，这是BUF数组，用户缓存所有的通知注册对象

BUF可以通过remove结束，但是_notice会一直延续，除关闭页面外其余页面_notice的生命周期将延续到页面关闭

**Comment by xilin** [comment]
OK，谢谢
